- deploy/config/local/.dory.yml
**Context** 
Issue https://github.com/ministryofjustice/justice-gov-uk/issues/17
> Very small security consideration

- .github/workflows/deploy.yml
> Correct syntax

- .github/README.md
- .github/workflows/integration.yml
- deploy/demo/config.yml
- deploy/demo/deployment.tpl
- deploy/demo/ingress.yml
- deploy/demo/secret.tpl
- deploy/demo/service.yml
- deploy/development/ingress.yml
- deploy/staging/config.yml
- deploy/staging/deployment.tpl
- deploy/staging/ingress.yml
- deploy/staging/secret.tpl
- deploy/staging/service.yml
Add files used in GitHub Action deployment.
This release will create the Demo and Staging environments.
> Add demo and staging Kubernetes deployment files

- docker-compose.yml
Hey @EarthlingDavey,
I have to apologise to you for this one. I'm just a little silly about the order. I am sorry!
> Move services to keep main on top

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/integration.yml
This PR creates one set of images and distributes them across deployments.
Environment variables control how the application behaves.
> Detach image build

- .env.example
- .github/README.md
- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/integration.yml
- Dockerfile
- composer.json
- composer.lock
- config/application.php
- config/environments/development.php
- config/wp-offload-media.php
- deploy/config/local/Caddyfile
- docker-compose.yml
- public/app/themes/justice/functions.php
- public/app/themes/justice/inc/amazon-s3-and-cloudfront-tweaks-for-minio.php
Add Minio for local development, it helps not using AWS locally for debugging.
Add verify, and document S3 & CloudFront settings.
> WP Offload Media - settings

- deploy/config/local/php-fpm.conf
- deploy/config/php-fpm.conf
Increases file size for uploads and post requests. 
Increases execution time to prevent timeout during uploads.
> Increase php limits to allow content import.

- public/app/themes/justice/404.php
- public/app/themes/justice/footer.php
- public/app/themes/justice/header.php
- public/app/themes/justice/page.php
- public/app/themes/justice/sidebar.php
- public/app/themes/justice/src/blocks/to-the-top/admin.js
- WP builtin 404 echos custom 404.html
- Use home_url function for on-site links. Hardcode header menu for now.
- Fix js bug where block function is called on non editing page.
- Amend sidebar: Fix bug where no post is present. Set depth to 1.
> Theme updates

- config/application.php
- public/app/themes/justice/functions.php
- public/app/themes/justice/inc/mail.php
In peer review of ticket: [CDPT-1314]( https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1154?issueParent=237022%2C195072&selectedIssue=CDPT-1314).
I noticed a couple of minor fixed that have been amended here.
[CDPT-1314]: https://dsdmoj.atlassian.net/browse/CDPT-1314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Notify amend

- public/app/themes/justice/inc/dynamic-menu.php
- public/app/themes/justice/inc/post-meta/constants.php
- public/app/themes/justice/src/components/simple-guten-fields/index.js
- public/app/themes/justice/src/js/block-editor.d.ts
- Add INTERSECTS operator to simple-guten-fields
- Add meta field _dynamic_menu_exclude_this
- Update dynamic menu to account for _dynamic_menu_exclude_this
- Update max menu items
> Post meta update no. 4

- .github/workflows/deploy.yml
- deploy/demo/secret.tpl
- deploy/development/secret.tpl
- deploy/staging/secret.tpl
I think this was previously set manually with kubectl.
> Generate ingress basic auth from GitHub secrets.

- public/app/themes/justice/search.php
- public/app/themes/justice/template-parts/search/search-bar.php
Previous implementation didn't read parent id form $arg, parent id must be passed for it to be read.
> CDPT-1077 Bug fix for in editor search block.

- public/app/themes/justice/inc/redirects.php
Ticket: https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1154?issueParent=237022&selectedIssue=CDPT-1561
> CDPT-1651 Redirect frontend urls appended with /_admin to the admin page.

- public/app/themes/justice/inc/post-meta/constants.php
- public/app/themes/justice/inc/post-meta/post-meta.php
Will allow the migration script and editors to add custom `<title> </title>` values.
> CDPT-1076 Add meta field for title tag.

- public/app/themes/justice/footer.php
- public/app/themes/justice/inc/search.php
- public/app/themes/justice/inc/taxonomies.php
- public/app/themes/justice/search.php
- public/app/themes/justice/src/components/core-rich-text/block-editor.js
- public/app/themes/justice/src/components/core-rich-text/editor.scss
- public/app/themes/justice/src/components/core-rich-text/frontend.scss
- public/app/themes/justice/src/components/core-rich-text/underline.js
- public/app/themes/justice/src/js/block-editor.js
- public/app/themes/justice/src/sass/app.scss
- public/app/themes/justice/src/sass/common.scss
- public/app/themes/justice/src/sass/editor.scss
- public/app/themes/justice/template-parts/panels/search-filters.php
- public/app/themes/justice/template-parts/search/content.php
- public/app/themes/justice/template-parts/search/search-bar.php
- Fix pagination - page 1 highlighting.
- Search results to show date created instead of date modified.
- Fix Web chats -> Webchats typo.
- Persist search filters across multiple searches.
- Add underline button for editors.
- Url encode search string to fix double quote searches.
> CDPT-1077: QA amends.

- public/app/themes/justice/src/css/global.css
- Remove old cookie banner styling
- Override default cookie button styling to meet accessibility standards
> CDPT-1541: Cookie banner

- deploy/production/config.yml
- deploy/production/deployment.tpl.yml
- deploy/production/hpa.yml
- deploy/production/ingress.yml
- deploy/production/secret.tpl.yml
- deploy/production/service.yml
This doesn't use www.justice.gov.uk as ingress yet.
> Copy demo deployment to production

- public/app/themes/justice/functions.php
- public/app/themes/justice/inc/sitemap.php
- Add new sitemap class
- Remove the users sitemap from wp-sitemap.xml
> CDPT-1631: Review sitemap

- public/app/themes/justice/inc/redirects.php
This PR adds functionality to handle cases where the content has internal links with URL paths that have commas (or other special chars) in them.
To avoid updating this content, let's handle these requests and redirect them to pages, if a page exists.
> PD 25b - Update redirects.php

- .github/workflows/integration.yml
Move demo down so it auto builds with dev and leaves staging for 2i
> Change order

- public/app/themes/justice/src/css/global.css
- Make full width
- Fix width of related pages box header
> Mobile layout

- deploy/development/ingress.yml
- deploy/local/ingress.yml
- Prevent traffic from thousandeyes
I _think_ this should work, but I've not been able to test it locally so will need to check on dev.
> CDPT-1633: Post deploy infrastructure amends

- public/app/themes/justice/src/sass/common.scss
**Before the update**
---
**Better alignment**
> Realign button

- public/app/themes/justice/src/patch/js/ccfw-cookie-manage.js
- public/app/themes/justice/src/patch/js/ccfw-frontend.js
Also, allowlist default to empty array
> If not jQuery bail

- Dockerfile
- public/app/themes/justice/src/patch/js/ccfw-check-consent.js
- public/app/themes/justice/src/patch/js/ccfw-cookie-manage.js
- public/app/themes/justice/src/patch/js/ccfw-frontend.js
- public/app/themes/justice/src/patch/js/ccfw-gtm.js
- public/app/themes/justice/src/sass/common.scss
Removes unused code
Add safeguards for jQuery undefined
Adds save button
A good general clean up
> Sentry errors take two

- public/app/themes/justice/src/patch/js/ccfw-frontend.js
- public/app/themes/justice/src/patch/js/ccfw-gtm.js
Addresses: https://ministryofjustice.sentry.io/issues/5453583632/?referrer=slack&notification_uuid=9b1d3f68-cba0-4274-aab3-b36d0695edac&environment=production&alert_rule_id=15208527&alert_type=issue
> Fix Object.hasOwn is not a function

- public/app/themes/justice/src/js/legacy/nselect.js
There is nothing extreme in this PR. Just an update to the JS file that includes:
- Performance: caching more than 50 redeclared jQuery objects
- Readability and syntax improvements
Sadly, the update means the file is completely changed, this doesn't help with review. Sorry about that!
> CDPT-1680 Refactor Nselect

- public/app/frontend/src/components/navigation-sections/index.js
- public/app/frontend/src/components/navigation-sections/navigation-sections.html.twig
- public/app/frontend/src/components/navigation-sections/navigation-sections.scss
- public/app/frontend/src/components/navigation-sections/navigation-sections.stories.js
- public/app/frontend/src/index.js
- Add navigation component
- Linting
- Use grid columns for mobile layout
> CDPT-1749: Navigation - sections

- Dockerfile
- deploy/development/ingress.yml
- deploy/production/ingress.yml
- deploy/staging/ingress.yml
Previous production ingress has been retained and set to weight 0, incase we need to rollback.
> Update ingress class to modsec

- public/app/frontend/base.scss
- public/app/frontend/src/components/navigation-secondary/navigation-secondary.stories.js
- public/app/frontend/src/components/sidebar-block/sidebar-block.stories.js
- public/app/frontend/src/decorators/sidebar.js
- Add sidebar decorator so sidebar elements are displayed in a more representative fashion
- Set UTF charset in base scss file so >> element is displayed consistently in breadcrumb element
> Styling tweaks

- public/app/frontend/src/layouts/one-sidebar/one-sidebar.html.twig
- public/app/frontend/src/layouts/one-sidebar/one-sidebar.scss
- public/app/frontend/src/layouts/two-sidebars/two-sidebars.scss
- Use the same structure for the single sidebar layout as is used in the two sidebar one so mobile panels are correctly positioned.
- Fix 'no descending selector specificity' error in scss
> Sidebar adjustments

- public/app/themes/justice/inc/documents/documents.php
Fixes https://ministryofjustice.sentry.io/issues/5735013307/?project=4506813195157504
> Rename isValidSlug function and set a default value.

- public/app/themes/justice/src/js/admin/request-errors.js
This PR will help us reduce the number of new issues created in sentry.
It will still keep all client-side 403s as unique issues, this will help in debugging and modsec false positives.
> Group client side errors by status code, except for 403s.

- public/app/themes/justice/inc/security.php
This PR removes a reference to non-existent a function.
> CDPT-2368 Remove unused filter.

- public/app/themes/justice/src/patch/js/ccfw-frontend.js
- Check whether the banner exists before getting the offset and top position
> CDPT-1994: TypeError: e().offset is undefined

- deploy/production/modsec-errors.tpl.yml
> CDPT-2640: Modsec

- deploy/production/ingress.tpl.yml
This PR copies ingress rules related to modsec custom error pages from dev/staging to prod.
> CDPT-2640 Add custom modsec error pages to prod.

- public/app/frontend/src/layouts/one-sidebar/one-sidebar.html.twig
- public/app/frontend/src/layouts/one-sidebar/one-sidebar.scss
- public/app/themes/justice/views/templates/home.html.twig
- Use the full grid on homepage, but otherwise limit paragraph width on single sidebar pages
> CDPT-2416: Help page design improvements

- spec/bootstrap.php
Fixes https://github.com/ministryofjustice/justice-gov-uk/issues/208
> Correct package in tests folder

- public/app/themes/justice/inc/security.php
This PR includes:
- a filter to respond to all requests for author pages with 404
- a filter to remove the 'View' link on the users admin screen
> CDPT-2910 Disable author pages

- public/app/frontend/src/components/link/link.html.twig
- public/app/frontend/src/components/navigation-main/navigation-main.html.twig
- public/app/frontend/src/components/navigation-secondary/navigation-secondary.html.twig
This PR adds `aria-current="page"` to active items in the primary (top) nav, and secondary (side) nav.
> CDPT-2865 Inform users of current page

- public/app/themes/justice/views/partials/footer.html.twig
- public/app/themes/justice/views/partials/header.html.twig
This is in line with WCAG and matches what is currently on production.
> CDPT-2867 Open header and footer links in same tab
