- deploy/development/config.yml
- deploy/development/ingress.yml
Routes the service to dev.justice.gov.uk
> Use dev.justice.gov.uk for development

- .env.example
- Dockerfile
- Makefile
- docker-compose.yml
This will allow the migration script (in a different local project) to use wp-cli remotely.
It can be used with the following arguments: `wp --ssh=ssh-user@host.docker.internal:2222/var/www/html db check` and will be useful for `import`ing from an xml file.
It cannot use dory because it's not http traffic. So it exposes the port to the host, and ssh commands for other containers use host.docker.internal
@wilson1000-MoJ do you mind taking a look, please.
- Is it ok to use a hardcoded password if this is only intended to be run locally?
- What's your opinion on me creating a dedicated container for this?
- Could you suggest a good way to add this to the Makefile. Currently I'm doing `docker compose --profile ssh up`.
> Add a container to allow wp-cli over ssh

- .github/workflows/deploy.yml
- deploy/demo/secret.tpl
- deploy/development/secret.tpl
- deploy/staging/secret.tpl
- public/app/themes/justice/inc/mail-templates.php
- public/app/themes/justice/inc/mail.php
**_Adds two scripts_**
1. mail.php - includes the `wp_mail` override functions
2. mail-templates.php - contains all available templates, prepared on Gov Notify
Updates `deploy.yml` and all associated `secret.tpl` files to inject an API secret.
> CDPT-1314 Add Gov Notify service

- deploy/demo/deployment.tpl
- deploy/development/deployment.tpl
- deploy/staging/deployment.tpl
Add `serviceAccountName` to deployments to associate IRSA links
Fixed Nginx deployment image referenece
> Add serviceAccount + fix dead nginx image ref

- config/application.php
I think there may be a couple of settings, that were not set in AS3CF_SETTINGS .e.g.:
- object-ownership-enforced
- block-public-access
For quicker trial and error, let's use the plugin's GUI to trail settings.
> Don't use AS3CF_SETTINGS, let's use the GUI during debugging.

- public/app/themes/justice/functions.php
- public/app/themes/justice/inc/errors.php
- public/app/themes/justice/page_errors.php
When WP_Error is called, it is up to the developer to access and handle the error, they are not logged by default.
This action/function ensures that any errors added to WP_Error will be logged immediately.
> Log WP_Errors

- Dockerfile
- public/app/themes/justice/inc/simple-guten-fields/simple-guten-fields.php
- public/app/themes/justice/webpack.mix.js
- webpack to copy asset.php files to `dist/php`
- update the path in php application
- Dockerfile
- Move `assets-build` above `build-fpm`
- minimise files copied over to `assets-build` from the codebase
- build-fpm to get `dist/php` from `assets-build`
> fix for missing asset.php file

- deploy/demo/ingress.yml
- deploy/development/ingress.yml
- deploy/local/ingress.yml
- deploy/staging/ingress.yml
Updates the deployments to allow file uploads < 200MB
- Docs: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#proxy-body-size
- Chat: https://mojdt.slack.com/archives/C57UPMZLY/p1647342791594759?thread_ts=1647342045.542929&cid=C57UPMZLY
- e.g. https://github.com/ministryofjustice/evidence-library/blob/main/src/kubectl_deploy/test-env/ingress.yaml
> Add nginx proxy-body-size annotation to allow for large file uploads.

- Dockerfile
- Makefile
- bin/composer-post-install.sh
- composer.json
- composer.lock
This causes documents to not upload.
Works locally. Once it's verified working locally it can be applied to intranet too.
> Fix typo in wp-document-revsions

- public/app/themes/justice/functions.php
- public/app/themes/justice/header.php
- public/app/themes/justice/inc/post-meta/post-meta.php
- public/app/themes/justice/inc/theme.php
The current theme had issues setting the `<title>` element on the homepage.
Adding theme support for `title-tag` is the recommended approach for fixing the issue. 
Reference:
- https://developer.wordpress.org/reference/functions/add_theme_support/
- https://stackoverflow.com/a/37223205/6671505
- https://wordpress.stackexchange.com/questions/305353/cant-change-the-title-tag-with-wp-title-filter
> CDPT-1076 Add theme support for title-tag.

- deploy/development/ingress.yml
- deploy/production/ingress.yml
This is working on dev so we can move it to prod. Requests with the X-Thousandeyes-Agent header receive a 403 response.
> CDPT-1633: Move thousand eyes ingress block to prod

- public/app/themes/justice/inc/plugin-hacks.php
Fixes: https://ministryofjustice.sentry.io/issues/5453583632/?environment=production&project=4506813195157504&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=1
> Version bump ccfw assets - clear old js from browser's cache.

- config/application.php
- deploy/config/local/server.conf
The endpoints: load-scripts.php and load-styles.php are used by WP to concatenate and compress assets at runtime.
Since we are using nginx, these assets can be served via nginx instead.
This PR makes the following changes:
- Disable the env vars: CONCATENATE_SCRIPTS, COMPRESS_CSS & COMPRESS_SCRIPTS
- Block the endpoints: load-scripts.php and load-styles.php - this change means they are not used but are DoS vectors.
This code is difficult to test locally because `Config::define('SCRIPT_DEBUG', true);` in `config/environments/development.php` means that scripts are not concatenated. Temporarily disable this and access an admin page locally to see `CONCATENATE_SCRIPTS` in action.
This should have the effect of fixing the intermittent CPU spikes. If not, it is still good practice :)
Further …
> Disable CONCATENATE_SCRIPTS, COMPRESS_CSS & COMPRESS_SCRIPTS

- public/app/themes/justice/src/components/core-rich-text/anchor.js
- public/app/themes/justice/src/sass/justice-theme.scss
- Amend validation to allow existing ids , and use named attributes
- Block editor page css fix. Open page button hidden was hidden, white space to the left of the update button. (@wilson1000 - a minor fix that I've bundled in here by increasing the specificty).
> Feature/cdpt 1704 - Amends - UI for inline anchor links

- composer.lock
For this PR, `composer update` was run. It updated the lock file and addresses:
- composer vulnerabilities as seen here https://github.com/ministryofjustice/justice-gov-uk/security/dependabot
- other outdated dependencies.
Update log:
```
- Upgrading codeception/module-db (3.1.3 => 3.1.4)
- Upgrading composer/class-map-generator (1.1.1 => 1.3.4)
- Upgrading composer/composer (2.7.6 => 2.7.7)
- Upgrading composer/pcre (3.1.3 => 3.1.4)
- Upgrading firebase/php-jwt (v6.10.0 => v6.10.1)
- Upgrading gettext/gettext (v4.8.11 => v4.8.12)
- Upgrading koodimonni-language/core-en_gb (6.5.3 => 6.5.4)
- Upgrading lucatume/wp-browser (4.1.7 => 4.2.4)
- Upgrading mockery/mockery (1.6.11 => 1.6.12)
- Upgrading myclabs/deep-copy (1.11.1 => 1.12.0)
- Upgrading psr/http-factory (1.0.2 => 1.1.0)
- Upgrading …
```
> security: composer update

- public/app/themes/justice/template-parts/panels/archived.php
- Update first link
- Add second 'to present' link
> CDPT-1906: Amending and adding new link to panel

- public/app/frontend/src/components/footer/footer.html.twig
- public/app/frontend/src/components/link/link.html.twig
- public/app/frontend/src/components/navigation-main/navigation-main.html.twig
- public/app/themes/justice/views/partials/footer.html.twig
- public/app/themes/justice/views/partials/header.html.twig
- Add correct links to footer and header in WP
- Add visually hidden prop for links that should open in new tabs - this lets us keep the structure of the header/footer whilst still communicating page changes to screen reader users
- Hide first gov.uk link from footer so that it's not repeated for screen reader users
> Accessibility improvements and link updates

- public/app/themes/justice/inc/admin.php
- public/app/themes/justice/package-lock.json
- public/app/themes/justice/package.json
- public/app/themes/justice/src/js/admin/index.js
- public/app/themes/justice/src/js/admin/request-errors.js
- public/app/themes/justice/src/js/utils.js
- public/app/themes/justice/webpack.mix.js
This can be tested by manually by:
- changing modsec ingress rules on development.
- triggering modsec false positives
- reviewing issue on Sentry
- Following link from Sentry UI to full log entry in OpenSearch.
> Send 403 errors to sentry, include a link (in Sentry) to Modsec logs.

- public/app/themes/justice/page.php
- public/app/themes/justice/page_home.php
- public/app/themes/justice/views/partials/header.html.twig
- Fix logic that displays the indicator (starts with permalink -> permalink starts with)
- Move footer function to the bottom of page/page_home
> CDPT-2073: Active indicator is missing on menu links

- Dockerfile
- bin/fpm-liveness.sh
- bin/fpm-readiness.sh
- bin/fpm-status.sh
- deploy/config/php-pool.conf
- deploy/config/server.conf
- deploy/demo/deployment.tpl.yml
- deploy/development/deployment.tpl.yml
- deploy/production/deployment.tpl.yml
- deploy/staging/deployment.tpl.yml
- public/app/object-cache.php
This PR adds heath checks for the php-fpm and nginx containers.
It then adds these endpoints and scripts to the kubernetes deployments.
These health checks are very similar to those on the intranet main branch. With the only difference being nginx readiness and liveness probes are going to the same uri (`/health`).
There are also 2 changes related to redis, they are duplicates from this pending PR https://github.com/ministryofjustice/justice-gov-uk/pull/282/files
> CDPT-2078 Add liveness and readiness health checks.

- public/app/mu-plugins/moj-auth/verify.php
- public/app/themes/justice/inc/search.php
- public/app/themes/justice/inc/security.php
This PR fixes recent bugs related to array conversion 
https://ministryofjustice.sentry.io/issues/?environment=production&project=4506813195157504&query=is%3Aresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D%20array&referrer=issue-list&statsPeriod=7d&utc=true
And, adds a couple of security fixes.
> CDPT-2368 Fix sentry errors

- Dockerfile
- deploy/demo/deployment.tpl.yml
- deploy/development/deployment.tpl.yml
- deploy/production/deployment.tpl.yml
- deploy/staging/deployment.tpl.yml
This PR makes the filesystem of the php-fpm container readonly. 
It also adds various security contexts to improve security of the pods.
> CDPT-2369 Make php-fpm container fs read only.

- public/app/themes/justice/src/js/block-editor/remove-custom-class.js
- Add an exception to the removeCustomClassNameSupport function for the list block
> CDPT-2268: Horizontal lists no longer have the 'is-style-page-nav' class

- deploy/config/php-pool.conf
- deploy/production/config.yml
This PR disable WP-Redis object cache, because it was increasing P99 latency to 10 seconds.
This PR also adds logging requests that take > ~8s
---
Further investigation is required to work out why the latency is increasing so much for a sub-set of requests.
This should include reviewing slow request logs, and adding logging for cache misses.
> CDPT-2574 Temp. disable redis

- deploy/config/server.conf
Currently, the requests related to scheduling are failing.
This is because the endpoint `/wp/wp-cron.php` is being hit, but nginx is trying to serve that file, instead of passing the request to `fpm`.
This PR is a change to the `server.conf` to match `local/server.conf`.
> Fix cron url returning 404

- public/app/frontend/src/components/footer/footer.scss
- public/app/frontend/src/documentation/design/Colours.mdx
- public/app/frontend/style.scss
This PR
- The link for  'Citizen and business advice' has an updated colour.
- The colours page in Story book is corrected and updated.
> CDPT-2868 Increase footer text contrast for 'Citizen and business advice'

- public/app/frontend/src/components/file-download/file-download.html.twig
- public/app/frontend/src/components/file-download/file-download.scss
- public/app/frontend/src/components/file-download/file-download.stories.js
- public/app/frontend/src/components/search-result-card/search-result-card.stories.js
- public/app/frontend/src/components/search-result-list/search-result-list.stories.js
- public/app/frontend/src/components/sidebar-block/sidebar-block.scss
- public/app/themes/justice/inc/templates.php
- public/app/themes/justice/views/partials/file-download.html.twig
- spec/Unit/TemplatesTest.php
This PR moves the download info e.g. `(PDF, 167 KB)` from after the file-download link, into inside the link.
Since this change, the inline and block variants of the file-download component are no longer necessary and have been removed.
> CDPT-2881 Move download info into link

- public/app/mu-plugins/cluster-helper/cluster-helper.php
- public/app/themes/justice/functions.php
- public/app/themes/justice/inc/security.php
- public/app/themes/justice/inc/updates.php
This PR ports over functionality from the Intranet
- Log http requests that connect to unknown domains.
- Don't connect to WordPress to check if core, plugins or theme is outdated.
> CDPT-3092 Log http requests to unknown domains
